const ENV = {
  API_ENDPOINT: import.meta.env.VITE_API_ENDPOINT,
  WALLETCONNECT_PROJECT_ID: import.meta.env.VITE_WALLETCONNECT_PROJECT_ID,
  APP_NAME: import.meta.env.VITE_APP_NAME,
  APP_LOGO: import.meta.env.VITE_APP_LOGO,

  // color
  PRIMARY_COLOR: import.meta.env.VITE_COLOR_PRIMARY || '#174BDE',
  SECONDARY_COLOR: import.meta.env.VITE_COLOR_SECONDARY || '#72EDF2',

  // layer 1
  L1_CHAIN_NAME: import.meta.env.VITE_L1_CHAIN_NAME,
  L1_CHAIN_ID: +import.meta.env.VITE_L1_CHAIN_ID,
  L1_RPC_URL: import.meta.env.VITE_L1_RPC_URL,
  L1_LOGO_URL: import.meta.env.VITE_L1_LOGO_URL,
  L1_NATIVE_CURRENCY_DECIMALS: import.meta.env.VITE_L1_NATIVE_CURRENCY_DECIMALS,
  L1_NATIVE_CURRENCY_NAME: import.meta.env.VITE_L1_NATIVE_CURRENCY_NAME,
  L1_NATIVE_CURRENCY_SYMBOL: import.meta.env.VITE_L1_NATIVE_CURRENCY_SYMBOL,
  L1_BLOCK_EXPLORER_NAME: import.meta.env.VITE_L1_BLOCK_EXPLORER_NAME,
  L1_BLOCK_EXPLORER_URL: import.meta.env.VITE_L1_BLOCK_EXPLORER_URL,
  L1_BLOCK_EXPLORER_API: import.meta.env.VITE_L1_BLOCK_EXPLORER_API,

  // layer 2
  L2_CHAIN_NAME: import.meta.env.VITE_L2_CHAIN_NAME,
  L2_CHAIN_ID: +import.meta.env.VITE_L2_CHAIN_ID,
  L2_RPC_URL: import.meta.env.VITE_L2_RPC_URL,
  L2_LOGO_URL: import.meta.env.VITE_L2_LOGO_URL,
  L2_NATIVE_CURRENCY_DECIMALS: import.meta.env.VITE_L2_NATIVE_CURRENCY_DECIMALS,
  L2_NATIVE_CURRENCY_NAME: import.meta.env.VITE_L2_NATIVE_CURRENCY_NAME,
  L2_NATIVE_CURRENCY_SYMBOL: import.meta.env.VITE_L2_NATIVE_CURRENCY_SYMBOL,
  L2_BLOCK_EXPLORER_NAME: import.meta.env.VITE_L2_BLOCK_EXPLORER_NAME,
  L2_BLOCK_EXPLORER_URL: import.meta.env.VITE_L2_BLOCK_EXPLORER_URL,
  L2_BLOCK_EXPLORER_API: import.meta.env.VITE_L2_BLOCK_EXPLORER_API,

  // l1 contract
  L1_MULTI_CALL3_ADDRESS: import.meta.env.VITE_L1_MULTI_CALL3_ADDRESS,
  L1_MULTI_CALL3_BLOCK_CREATED: import.meta.env
    .VITE_L1_MULTI_CALL3_BLOCK_CREATED,
  L1_ENS_REGISTRY_ADDRESS: import.meta.env.VITE_L1_ENS_REGISTRY_ADDRESS,
  L1_ENS_UNIVERSAL_RESOLVER_ADDRESS: import.meta.env
    .VITE_L1_ENS_UNIVERSAL_RESOLVER_ADDRESS,

  // l2 contract
  L2_MULTI_CALL3_ADDRESS: import.meta.env.VITE_L2_MULTI_CALL3_ADDRESS,

  // bridge address
  DISPUTE_GAME_FACTORY_PROXY: import.meta.env.VITE_DISPUTE_GAME_FACTORY_PROXY,
  L2_OUTPUT_ORACLE_PROXY_ADDRESS: import.meta.env
    .VITE_L2_OUTPUT_ORACLE_PROXY_ADDRESS,
  PORTAL_PROXY_ADDRESS: import.meta.env.VITE_PORTAL_PROXY_ADDRESS,
  L1_STANDARD_BRIDGE_PROXY_ADDRESS: import.meta.env
    .VITE_L1_STANDARD_BRIDGE_PROXY_ADDRESS,
  L1_CROSS_DOMAIN_MESSENGER_PROXY_ADDRESS: import.meta.env
    .VITE_L1_CROSS_DOMAIN_MESSENGER_PROXY_ADDRESS,
  L1_ERC721_BRIDGE_ADDRESS_PROXY: import.meta.env
    .VITE_L1_ERC721_BRIDGE_ADDRESS_PROXY,
  L2_STANDARD_BRIDGE_PROXY_ADDRESS:
    import.meta.env.VITE_L2_STANDARD_BRIDGE_PROXY_ADDRESS ||
    '0x4200000000000000000000000000000000000010',
  L2_L1_MESSAGE_PASSER_ADDRESS: '0x4200000000000000000000000000000000000016',
  WITHDRAWAL_PERIOD : +import.meta.env.VITE_WITHDRAWAL_PERIOD || 180,
  STATE_ROOT_PERIOD: +import.meta.env.VITE_STATE_ROOT_PERIOD || 180,
};

export default ENV;
