// DO NOT MODIFY THIS FILE IS AUTOGENERATED
import type { Chain } from "viem/chains";
import {
  base,
  baseSepolia,
  mainnet,
  optimism,
  optimismSepolia,
  pgn,
  pgnTestnet,
  sepolia,
  zora,
  zoraSepolia,
} from "viem/chains";

import { NetworkPairGroup } from "./opType";
import { l1Chain, l2Chain } from "./chain";

export type NetworkType =
  | "base"
  | "op"
  | "pgn"
  | "zora"
  | "main";

export const networkPairsByGroup: NetworkPairGroup = {
  base: {
    mainnet: [mainnet, base],
    sepolia: [sepolia, baseSepolia],
  },
  op: {
    mainnet: [mainnet, optimism],
    sepolia: [sepolia, optimismSepolia],
  },
  pgn: {
    mainnet: [mainnet, pgn],
    sepolia: [sepolia, pgnTestnet],
  },
  zora: {
    mainnet: [mainnet, zora],
    sepolia: [sepolia, zoraSepolia],
  },
  main: {
    mainnet: [l1Chain, l2Chain],
  },
};

export const networkPairsByID: Record<number, [Chain, Chain]> = {
  8453: [mainnet, base],
  10: [mainnet, optimism],
  424: [mainnet, pgn],
  7777777: [mainnet, zora],
  84532: [sepolia, baseSepolia],
  // 11155420: [l1ChainConfig, l2ChainConfig],
  58008: [sepolia, pgnTestnet],
  999999999: [sepolia, zoraSepolia],
  [l2Chain.id]: [l1Chain, l2Chain],
};
